### REF: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/examples/kubernetes/dynamic_provisioning/specs/storageclass.yaml

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisionMode: efs-ap
    ## export EFS_ID=$(aws efs describe-file-systems --query "FileSystems[?Name=='$EKS_CLUSTER_NAME-efs-assets'] | [0].FileSystemId" --output text)
    ### echo $EFS_ID
  filesystemId: ${EFS_ID}
  directoryPerms: "700"
    ###   gidRangeStart: "1000" # optional
    ###   gidRangeEnd: "2000" # optional
    ###   basePath: "/dynamic_provisioning" # optional
    ###   subPathPattern: "${.PVC.namespace}/${.PVC.name}" # optional
    ###   ensureUniqueDirectory: "true" # optional
    ###   reuseAccessPoint: "false" # optional
